
# 异常
-   分类：
    -   `Error`：致命的
    -   `Exception`：非致命，可以捕获处理使程序继续运行，可分为运行时异常和非运行时异常

## `Exception`

-   运行时异常：<br>
    `RuntimeException`类及其子类，一般由程序逻辑错误引起 
    | 异常类 | 含义| 
    | --- | --- |
    | `ArrayIndexOutOfBoundsException` | 数组下标越界 |
    | `ArithmeticException` | 算数异常 | 
    | `ArrayStoreException` | 数组包含不兼容的值的抛出异常 | 
    | `ClassCastException` | 类型转换异常 | 
    | `FileSystemNotFoundException` | 文件系统未找到异常 | 
    | `IllegalArgumentException` | 非法参数 |
    | `IndexOutOfBoundsException` | | 
    | `NullPointerException` | 空指针 | 
    
    //--------------------------------------------
    <br>//  *书 P192，待补充*<br>
    //--------------------------------------------

-   非运行时异常：不处理就没法编译 
    | 异常类 | 含义 | 
    | --- | --- |
    | `ClassNotFoundException` | 未找到类 | 
    | `FileNotFoundException` | 文件未找到 | 
    | `IOException` | 输入输出流异常 | 
    | `TimeoutException` | 操作超时 | 
    | `SQLException` | 操作数据库异常 |

    -   对于非运行时异常，必须使用`try···catch`代码块处理或使用`throw`关键字抛出

## 异常捕获

1.  `try···catch`代码块
    ```
        try{       
            //程序代码块     
        }catch(ExceptionType e1){
           //对e1的处理     
        }catch(ExceptionType e){       
            //对e的处理，常见有：       
            //e.getMessage();     //有关异常的信息       
            //e.toString();       //有关异常的类型与性质       
            //e.printStackTrace() //获取异常发生时执行堆栈的内容     
        }finally{       
            //代码，可选。不论程序是否异常都会执行       
            //常常放置一些诸如释放资源、关闭对象的代码     
        }
    ```
    -   注意：使用多个catch时，父类异常必须在子类异常后
    -   Exception是try块传给catch的类型，e是对象
    -   除非含有以下三种情况，否则finally都会执行
        1.  finally里有异常
        2.  前面的代码使用了System.exit()推出程序
        3.  所在的线程死亡
2.  抛出异常

-   `throws`
    <br>通常在方法被声明时用来指定方法可能抛出的异常，多个异常可用逗号分隔
    ```
    [返回值类型] [方法名](参数表) throws [异常类型名] {         
        //方法     
    }
    ```

    -   使用throws为方法抛出异常时，若子类继承父类，子类重写方法抛出的异常应是父类异常（或其子类），除非throws异常是`RuntimeException`

    -   若某方法抛出了异常，在调用时必须处理异常。若不想处理，可继续向上一级抛出，但最终必须处理

-   `throw` <br>通常在方法中制造一个异常，执行到throw时立即终止
    ```
    throw new [异常类型名](异常信息)
    ```

    -   通常用于在某种逻辑错误时人为抛出并终止

    -   throw常常用来抛出自定义异常

-   throws和throw关键字的区别

    -   throws用在方法声明后面，表示抛出异常，由方法调用者处理；
        <br>throw用在方法体内，用来制造异常
    -   throws声明抛出异常的类型，throw直接抛出异常实例
    -   throws表示表现异常的可能，throw一定有异常

## 自定义异常

-   通过继承Exception类自定义异常
    1.  创建自定义类
    2.  throw出异常对象
    3.  若在当前抛出异常的方法中处理异常，使用try···catch，否则在方法的声明处用throws关键字指明要抛给方法调用者的异常，继续下一步
    4.  在出现异常方法的调用者中捕获、处理异常

### tips

-   不要过多使用异常
-   自定义异常可更详细的显示错误
-   避免使用**catch(Exception e)**，防止所有异常都采用相同的处理方式
-   try···catch不能太大
